name: Deploy to Production

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Change to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
      env:
        VITE_NASA_API_KEY: ${{ secrets.VITE_NASA_API_KEY }}

    - name: Deploy
      run: |
        # Add your deployment commands here, e.g., for Netlify or Vercel
        echo "Deploying..."
